### PR TITLE
Modular restructuring

### PR DESCRIPTION
**Pull request by Emaziz**
@Illyohs you mentioned modularity

I reorganized all the files in new packages based on their feature, as seen in the images below
[Package structure](https://imgur.com/lKt1HYS)
[All files](https://imgur.com/7wlXsOS)

With this structure the command loader could easily be modified to include/exclude entire features based on their package. The server configuration file could contain a set of rules defining which packages to exclude/include in addition to specific commands if wanted.

```
commandRules { # All enabled by default
	exclude {
		"com.dragontechmc.dtessentials.moderator" # if another management plugin was wanted
		"com.dragontechmc.dtessentials.player.kit"
	}
	include {
		"com.dragontechmc.dtessentials.moderator.ticket" # we want to keep tickets though
	}
}
```

### CODE REVIEW

**Comment by Illyohs** [comment]
The restructure yes but the commands rules should not require the classpath of the command. Its to verbose for normal users IMO and I do not expect them to look at the GitHub to simply disable commands I believe we would be better suited off using something like this.

````
commands {
   "afk": true
   "sethome": true
   "delhome": true
   "home": true
   "cheatallthethings":false
}
````

**Comment by Emaziz** [comment]
72b0455 allows commands to be disabled in the config file. 

Format:
```
module {
    chat:false
}
commands {
    message:true
}
```
Behaviour:
 - If a command is specified in commands it overrides the module setting
 - A module is named by its packages last sub-package. e.g. `com.dragontechmc.dtessentials.player.kit` is named `kit`
 - Disabling a module will not disable its submodules

**Comment by Illyohs** [comment]
Will be merged into testing please squash

**Comment by Emaziz** [comment]
Squashed

**Comment by Illyohs** [comment]
Merged into testing e88e8a40986c5df82a67aeff7ad8c822c676f54a

**Pull request closed without merging**
